    CREATE TABLE IF NOT EXISTS CARD_SUIT (  
    id INT AUTO_INCREMENT PRIMARY KEY,  
    suit VARCHAR(50) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS CARD_TYPE (  
    id INT AUTO_INCREMENT PRIMARY KEY,  
    type_value VARCHAR(50) NOT NULL,
    type_description VARCHAR(50) NOT NULL
    );
    
    CREATE TABLE IF NOT EXISTS CARD (  
    id INT AUTO_INCREMENT PRIMARY KEY,  
    id_suit INT NOT NULL,
    id_type INT NOT NULL,
    CONSTRAINT FROM_CARD_TO_CARD_SUIT_ID FOREIGN KEY (id_suit) REFERENCES CARD_SUIT (id),
    CONSTRAINT FROM_CARD_TO_CARD_TYPE_ID FOREIGN KEY (id_type) REFERENCES CARD_TYPE (id)
    );